-- Create accounts table
CREATE TABLE ACCOUNTS (
    ACC_ID BIGINT PRIMARY KEY,
    ACC_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    BAL DECIMAL(15, 2)
);

-- Create transactions table
CREATE TABLE TRANSACTIONS (
    TRNS_ID BIGINT PRIMARY KEY,
    ACC_ID BIGINT,
    AMT DECIMAL(15, 2),
    TRNS_TYPE VARCHAR(10), -- 'credit' or 'debit'
    TRNS_TS TIMESTAMP,
    FOREIGN KEY (ACC_ID) REFERENCES ACCOUNTS(ACC_ID)
);
